### ISSUE TITLE
MoonTimes suspicious value!

### ISSUE THREAD

**Issue by rudrab** [shred/commons-suncalc#5] opened 2018-03-01 19:17 UTC
Suddenly it has started giving rise=null.
Can you kindly check if that is normal?
`03-02 00:44:25.398 5274-5274/com.example.phocast I/System.out: MOONTIME=========MoonTimes[rise=null, set=Fri Mar 02 11:57:24 GMT+05:30 2018, alwaysUp=false, alwaysDown=false]`

This is the call:
`    MoonTimes moontime = MoonTimes.compute().at(latlang.Lat,latlang.Lang).today().execute();
`

**Comment by shred** [comment] 2018-03-02 11:32
It's not unusual. The moon is already up at midnight of that day, sets at 11:57, and does not rise again that day (but maybe short past next midnight). However, can you give me the name of the city your test coordinates belong to?

**Comment by rudrab** [comment] 2018-03-02 12:54
Hi Shred,
Thanks a lot for your explanation. In this case, can I grab the next moonrise and moonset(i mean today or if already up today, then tomorrow)? I know i can use that conditional in my code as well, but wondering if this is inbuilt in the library.
Its Allahabad, India.

**Comment by shred** [comment] 2018-03-02 20:32
You just need to add `.fullCycle()` to your chain of parameters. The library will then compute until the moonrise and moonset times are available, even if not on the same day.

This time, [it is documented](https://shredzone.org/maven/commons-suncalc/usage.html#Time_Range). :wink:

**Comment by shred** [comment] 2018-03-03 11:28
What irritates me is that I am getting a completely different result for presumably the same parameters:

```
MoonTimes[rise=Fri Mar 02 18:31:23 IST 2018, set=Fri Mar 02 06:36:34 IST 2018, alwaysUp=false, alwaysDown=false]
```

My code:

```java
TimeZone.setDefault(TimeZone.getTimeZone("IST"));
System.out.println(MoonTimes.compute().on(2018, 3, 2).at(25.452778, 81.863889).execute());
```

**Comment by rudrab** [comment] 2018-03-06 04:10
thats really imitating. any clue?

**Comment by shred** [comment] 2018-03-06 21:51
I don't know... Do you use similar coordinates for Allahabad? 25.452778 N, 81.863889 E

If you run my example, do you get the same result?

**Comment by rudrab** [comment] 2018-03-07 05:00
Yes, actually off late, I have never seen the null value.
One more thing, with suntime parameters, like say bluehour, I get getRise in morning time and getset on evening. Is there any way to get time of morning bluehour start and end, and so for the evening, separately?

**Comment by shred** [comment] 2018-03-07 08:30
> Yes, actually off late, I have never seen the null value.

They are rare, but they can occur. Your code should be aware of that.

> Is there any way to get time of morning bluehour start and end, and so for the evening, separately?

No. You would have to get the `SunTimes` for the bluehour start twilight and bluehour end twilight separately. Then you have all the times you want.

**Comment by rudrab** [comment] 2018-03-11 18:26
Hi Shred, I guess I failed to explain you my problem.
I have defined Golden Hour as:
```
SunTimes ghst = SunTimes.compute()
        .today().at(latlang.Lat,latlang.Lang)
        .twilight(SunTimes.Twilight.GOLDEN_HOUR)
        .execute();
  String ghr = localDateFormat.format(ghst.getRise());
  String ghs = localDateFormat.format(ghst.getSet());

```

For the latitude and longitude I have given, I am getting value for ghr at morning(06:46IST) and ghs at evening(17:39 IST).

But what I am looking for is ghr as golden hour start time in morning, evening separately, and so for the evening, at local time.

Is that possible?

**Comment by shred** [comment] 2018-03-11 21:15
I'm not sure if I understand you correctly. There is no defined end of Golden Hour. However, we could say that "Golden Hour" starts with sunrise and ends with sunset. You could get all four times like this:

```java
SunTimes.Parameters param = SunTimes.compute()
        .today().at(latlang.Lat,latlang.Lang);

SunTimes ghst = param.twilight(SunTimes.Twilight.GOLDEN_HOUR)
        .execute();

SunTimes visualst = param.twilight(SunTimes.Twilight.VISUAL)
        .execute();

// Morning Golden Hour starts here:
String dawn = localDateFormat.format(visualst.getRise());

// Morning Golden Hour ends here:
String ghr = localDateFormat.format(ghst.getRise());

// Evening Golden Hour starts here:
String ghs = localDateFormat.format(ghst.getSet());

// Evening Golden Hour ends here:
String dusk = localDateFormat.format(visualst.getSet());
```

Is this what you are looking for?

**Comment by rudrab** [comment] 2018-03-12 02:20
Hi,
Thanks a lot for your comment and help. Yes, thats definitely what I am looking for. So, is that same for other twilight parameters, eg blue, nautical etc?

**Comment by shred** [comment] 2018-03-12 09:20
Yes, you can just change single parameters, and get the new result by invoking `execute()`. This is by design. It would be the same for `SunTimes.Twilight.BLUE_HOUR` and `SunTimes.Twilight.CIVIL`, or what combination you like.

I'm not sure what lag you mean, but if you need a different twilight angle, you can also pass it in as a double value:

```java
SunTimes ghst = SunTimes.compute()
        .today().at(latlang.Lat,latlang.Lang)
        .twilight(-8.0)  // in degrees
        .execute();
```

**Comment by shred** [comment] 2018-03-19 14:54
There was not really an issue with suncalc, so I'm closing this bug now.

**Closed by shred** 2018-03-19 14:54 UTC

**Comment by rudrab** [comment] 2018-03-19 15:49
sure, and thanks  a lot
