### ISSUE TITLE
Bug, Android Termux with Java: no main manifest attribute

### ISSUE THREAD

**Issue by lexterror** [shred/commons-suncalc#39] opened 2023-04-12 08:34 UTC
Hi 

![Screenshot_20230412-043254](https://user-images.githubusercontent.com/16135535/231400686-0b14506c-3cda-43a7-bbac-104058c1b759.png)

**Comment by lexterror** [comment] 2023-04-12 09:19
https://www.javatpoint.com/no-main-manifest-attribute

**Comment by shred** [comment] 2023-04-12 09:30
`no main manifest attribute` means that there is no main class that Java could execute. Since suncalc is a library, this is the expected behavior. The purpose of suncalc is to help other programs with the calculation, but it is not an app in itself.

Closing because it is not a bug.

**Closed by shred** 2023-04-12 09:30 UTC

**Comment by lexterror** [comment] 2023-04-12 12:16
thank you! 

I was hoping it was a cli app.
