### ISSUE TITLE
Subarctic spring sunsets and winter sunrises can be missed

### ISSUE THREAD

**Issue by isomeme** [shred/commons-suncalc#21] opened 2020-06-06 23:01 UTC
First, thanks for v3.0! It's wonderful being able to use java.time directly, though I would have gone with Instant rather than ZonedDateTime. But I'm kind of a crazy purist, so take that with a grain of salt. :) And the noon/nadir accuracy is *massively* better. Nice work. I look forward to digging into the code again to see what you did.

Meanwhile, I don't know whether you'll consider this a bug or a feature request, but SunTimes in non-fullCycle mode misses sunrises or sets that occur just over 24 hours after the preceding one. I cleaned out all my old SunCalc tests after looking through your own ones, so my [SunCalcTest](https://github.com/isomeme/Helios/blob/master/helios/src/test/java/org/onereed/helios/sun/SunCalcTest.java) class now has just one test, demonstrating what I'm talking about. 

It seems like having non-fullCycle mode keep looking some reasonable time past 24 hours would fix this, and make the behavior more useful. As it stands, if I want to be sure to catch these just-over-the-line cases, I have to do two SunTimes calls and combine the results.

**Comment by isomeme** [comment] 2020-06-06 23:06
A related question: getNoon() and getNadir() are now annotated as @Nullable in v3.0. Under what conditions will they be null? Are they subject to the same issue I found for rise and set? I notice the API doc says these values aren't affected by fullCycle, which makes this even more puzzling.

**Comment by shred** [comment] 2020-06-07 08:52
I decided to use `ZonedDateTime` because `Instant` does not carry the timezone the calculation was based on. It would give results that look strange on the first sight, e.g. if your system is located in Paris and you calculate the sunrise in New York, an `Instant` result would look like the sun rises in New York at around noon. With `ZonedDateTime` it is always clear what timezone the result is related to. And as a side benefit, you can use methods like `.getHour()` to easily read the result. I agree that it seems to be overly complicated if you are only using your local timezone. But you can still use `.toInstant()` to get the `Instant` of a result.

Non-fullCycle() is meant as a 24-hour mode. My intention was to start the calculation at midnight, and then use the 24-hour mode to only find the events of the very same day. But then again, that 24-hour mode is always a source of confusion. For v3.0, I was pondering to make fullCycle the default, but I decided against it. I think it was a mistake now.

`getNoon()` and `getNadir()` have always been `@nullable`. The missing annotation was just kept undetected until I switched from JSR305 to SpotBugs annotations. `null` is returned if there is no noon/nadir within the next 24 hours (e.g. summer above the Arctic Circle). Yes, here we go again with the confusions caused by the fullCycle mode. `getNoon()` and `getNadir()` only consider the next 24 hours, irregarding of the fullCycle mode.

Thinking of it again, I think I will make fullCycle the default, and publish a v3.1 asap.

**Comment by shred** [comment] 2020-06-07 13:53
`fullCycle()` is the default in v3.1 now. I hope it will settle all the confusion about the `SunTimes` results. :smile:

**Comment by isomeme** [comment] 2020-06-07 22:05
Yeah, that's probably simplest, though users in Pt. Barrow will curse you for burning through their phone's battery half the year. :)

**Comment by isomeme** [comment] 2020-06-08 04:32
I migrated to 3.1, and in working on my own app today found [a simple case](https://github.com/isomeme/Helios/blob/master/helios/src/test/java/org/onereed/helios/sun/SunCalcTest.java) where noon is still off by nearly a degree. :(

**Comment by shred** [comment] 2020-06-08 14:56
Yes, it's a stupid bug that I introduced in v3.1. It's going to be fixed in the next release.

The users in Pt. Barrow could use the new `limit()` parameter. :wink:

**Comment by isomeme** [comment] 2020-06-08 18:16
First, great, I'll watch for that release. Second, sorry I put this on the wrong bug. And third, cool point on Pt. Barrow. Literally. :)

**Comment by shred** [comment] 2020-06-11 06:52
Besides the precision regression, is everything else is resolved for you now? I want to avoid getting into a cycle where I make a release, you find another bug, and I make a new release just a few days later.

So if you give me a thumbs-up, I'll release the new version immediately. :smile:

**Comment by shred** [comment] 2020-06-11 17:51
v3.2 is released and should be available on maven central soon!

Yes, please find more bugs! I know it's hard to find good testers, so I appreciate your work. :smiley:

**Comment by isomeme** [comment] 2020-06-18 03:29
By the way, on the original topic of this bug, I consider the limit() mechanism to have resolved the problem.

**Comment by shred** [comment] 2020-06-18 05:10
Thanks! I will close this bug then.

**Closed by shred** 2020-06-18 05:10 UTC
